<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-ILMNV9M" ignored="6" name="Default test" tests="2" failures="1" timestamp="13 十二月 2017 01:22:43 GMT" time="43.843" errors="0">
  <testcase name="testBackLogin" time="12.153" classname="CommentManagement.CMsearchTest"/>
  <testcase name="sear6" time="23.008" classname="CommentManagement.CMsearchTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at CommentManagement.CMsearchTest.sear6(CMsearchTest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- sear6 -->
  <testcase name="sear1" time="0.0" classname="CommentManagement.CMsearchTest">
    <ignored/>
  </testcase> <!-- sear1 -->
  <testcase name="sear7" time="0.0" classname="CommentManagement.CMsearchTest">
    <ignored/>
  </testcase> <!-- sear7 -->
  <testcase name="sear5" time="0.0" classname="CommentManagement.CMsearchTest">
    <ignored/>
  </testcase> <!-- sear5 -->
  <testcase name="sear4" time="0.0" classname="CommentManagement.CMsearchTest">
    <ignored/>
  </testcase> <!-- sear4 -->
  <testcase name="sear3" time="0.0" classname="CommentManagement.CMsearchTest">
    <ignored/>
  </testcase> <!-- sear3 -->
  <testcase name="sear2" time="0.0" classname="CommentManagement.CMsearchTest">
    <ignored/>
  </testcase> <!-- sear2 -->
</testsuite> <!-- Default test -->
